# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5ebe485a1c5599d21f936c3cb577e7ccbd09e9863d00fccde7bb5280e8c463f3f928ffa669313f4daeba4f1929500e1add526706f6f18d58dcae747419d4340

test:
  secret_key_base: 6f3b9d07fdcb9dba5e7e4ed47213dfe60a511a7a6dfa1cb6dc15d6d512d0777911ed098cd54c14a483d4af0d4d9692f16b6657d67217c18612147b10a45518fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
